### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Andy0570** [ebelinski/iosref#10]
Here are the useful sites I recommend: 

* [Xcode Build Settings](https://xcodebuildsettings.com/)
* [Easing functions Cheat Sheet](https://easings.net/)
* [quicktype.io](https://app.quicktype.io/)
* [JSONLint](https://jsonlint.com/)

**Comment by ebelinski** [comment]
Hey @Andy0570, I added Xcode Build Settings, but the other suggestions are not directly related to iOS so I am hesitant about adding them.
