### ISSUE TITLE
How are `vintage` and `obsolete` defined?

### ISSUE THREAD

**Issue by bartekpacia** [ebelinski/iosref#13]
Would be nice to explain it on the website, e.g near the footer.

**Comment by ebelinski** [comment]
Hi @bartekpacia, that's a good question. I obtained this information from [this Apple support page](https://support.apple.com/en-us/HT201624), but I forgot to link to it on the website. I've updated the relevant pages to link to this now. Let me know if you have any other suggestions. Thanks!

**Comment by bartekpacia** [comment]
Great, thank you :)
